--- 
description: "Blog about software development, mainly in PHP, Android, Docker and Java and Product Development ideas based on my readings."
excerpt_separator: ""
markdown: kramdown
paginate: 5
pygments: true
tagline: "Software development and product development"
title: "Nil Portugués Calderó"
url: "http://nilportugues.github.io"
